
docker:
  image: "ubuntu:14.10"

install:
  - "sudo apt-get update"
  - "yes | sudo apt-get install git php5-cli"
  - "git clean -fdq"
  - "wget https://getcomposer.org/download/1.0.3/composer.phar"
  - "php composer.phar self"
  - "php composer.phar install"
merge:
  script: |
    php ./vendor/bin/phpunit
  fast-forward: only
  rebase: true
